In [2]:
# Perform following operations based on NumPy – Indexing & Slicing
# a. Slice first five elements from an array
# b. Access the last element of an array
# c. Extract the second row from a 2D array
# d. Reverse a NumPy array
import numpy as np
# Create a sample 1D NumPy array
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])
print("Original Array:", arr)
# a. Slice first five elements from the array
first_five = arr[:5]
print("First five elements:", first_five)
# b. Access the last element of the array
last_element = arr[-1]
print("Last element:", last_element)
print()
# Create a 2D NumPy array
arr_2d = np.array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]
])
print("2D Array:")
print(arr_2d)
# c. Extract the second row from the 2D array
second_row = arr_2d[1]
print("Second row:", second_row)
# d. Reverse the NumPy array
reversed_arr = arr[::-1]
print("Reversed array:", reversed_arr)


Original Array: [10 20 30 40 50 60 70 80]
First five elements: [10 20 30 40 50]
Last element: 80

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Second row: [4 5 6]
Reversed array: [80 70 60 50 40 30 20 10]
